### ISSUE TITLE
Enabling kiosk mode leaves white space at the bottom of the tablet

### ISSUE THREAD

**Issue by MantasIgnatjevas** [matt8707/kiosk-mode#4] opened 2020-10-20 07:53 UTC
![5A853F98-E92F-4531-A27B-5D5572968098](https://user-images.githubusercontent.com/25037128/96556918-44abd780-12c2-11eb-8277-0774856eba80.jpeg)

So this is the issue in the picture. 
The main container background is an image. The sidebar background is a css code. 

For whatever reason this does not seem to work. When inspecting with developer tools the white space is not a seperate part, its just the main view as is everything else. 

Any help is much appreciated.

**Comment by KTibow** [comment] 2020-10-20 13:54
Duplicate of #2

**Comment by MantasIgnatjevas** [comment] 2020-10-20 14:29
> Duplicate of #2

It is not. Mine has two parts with main area and sidebar, the white space is uneven, one is css code, one is image. This is completely different.

**Comment by matt8707** [comment] 2020-10-24 13:11
The aspect ratio of your layout is not the same as your tablet. 

You can correct that or you can add a background to fill up the whitespace.

```
      card-mod-root: |
        ha-app-layout {
          background: url('/local/background.png') !important;
          background-size: cover !important;
        }
```

**Comment by Johmpa** [comment] 2020-10-27 09:15
I'm seeing a similar thing with my dashboard. It is as though the theme background loads before the header disappears and isn't resized to the new space.

**Comment by gamer06** [comment] 2020-10-28 21:54
Hi. I have the same problem...
It doesn't appear on all cards, but it does. How can it be resolved, I don't understand?
Thanks

**Comment by MantasIgnatjevas** [comment] 2020-10-29 09:34
What matt wrote did help with the main view, I just set my background that way instead of the raw configuration editor. Then there was the problem with sidebar, but since the new background setup coveres the bottom part of the sidebar, I just changes the sidebar color code to the one of the background. Its not ideal, since I would like my sidebar different color, but good enough for the time being.

**Closed** 2020-11-01 09:30 UTC

**Comment by maykar** [comment] 2020-11-01 13:02
This hasn't been released yet, so don't expect it to be fixed until that happens. My PR that mentions this issue has just been merged.
