### ISSUE TITLE
iOS 12.5.4 (and lower) refreshing issues with HA app on 2021.6+

### ISSUE THREAD

**Issue by maykar** [matt8707/kiosk-mode#69] opened 2021-06-30 22:19 UTC
Originally posted by @milkplus27:

"Hi there. I've been running kiosk_mode on an iPad Mini 2 pretty flawlessly for about 3 weeks and today it's started to act up. upon loading the HA app, it will display properly with sidebar and header hidden, but once Lovelace refreshes (for whatever reason) both the sidebar and header will reappear and it's necessary to force quit the app and reopen to get kiosk_mode to reinitialise (only for it to break again when lovelace refreshes).

I updated to 2021.6 which I think may be the problem... however, i've also just switched over to a new router but I don't see how that would affect things. Anyone experienced anything similar? I have kiosk_mode set by user, if that makes any difference?"

**Comment by maykar** [comment] 2021-06-30 22:21
For those that are having this issue, please post the iOS version and devices that have these issues.

**Comment by LEJOUI** [comment] 2021-07-01 07:13
iOS 12.5.4 on an IPad mini 2

**Comment by milkplus27** [comment] 2021-07-01 07:50
Yup, 4x iPad Mini 2's running iOS 12.5.4

**Comment by maykar** [comment] 2021-07-01 11:16
I'm sure I have an iPad that is also locked at 12.5.4. Unfortunately I am in the process of moving so it is likely in storage, fortunately I'm finally moving in this weekend and will make finding and testing it a priority once things settle down a bit.

Is this happening in Safari and the iOS app or just the iOS app?

**Comment by maykar** [comment] 2021-07-01 11:28
Is this happening in Safari and the iOS app or just the iOS app?

**Comment by milkplus27** [comment] 2021-07-01 14:46
Unfortunately I rolled back to 2021.5.5 because my dashboards became practically unusable due to constant refreshing. So am unable to check if the same issue is present outside of the HA companion app

**Comment by LEJOUI** [comment] 2021-07-01 15:43
It looks like it's an app thing to me over here. In safari I don't have the refresh and adding HA to the Home Screen and then run guided acces seems to work.

**Comment by stephenmetts** [comment] 2021-07-04 14:17
As a user running version 1.7.1 of this with latest HA version on a fire tablet with Fully Kiosk browser, this issue does reproduce. I’d be happy to help test if needed. Thanks in advance for continuing to maintain this awesome add on!

**Comment by maykar** [comment] 2021-07-06 16:36
@stephenmetts this seems to be an iOS HA app issue only. The temporary solution for anyone in this situation [was posted by LEJOUI](https://github.com/maykar/kiosk-mode/issues/69#issuecomment-872352192). I'll still be searching for a solution for the HA companion app.

**Comment by FidgetyRat** [comment] 2021-07-07 14:02
I'm having the issue under 12.5.4 on an iPhone 5s NOT using the HA app. I use a kiosk browser called "WebFrame" that also worked fine until 2021.6+

Similar issue as reported. Works fine on initial page load for maybe 30 seconds then gets in a "refresh" loop every 10 seconds or so. Sidebars reappear.

Eventually after enough (unknown number) of refreshes, the page (view) just goes blank white with only the HA bar visible. I need to manually refresh to get it all to return.

**Comment by milkplus27** [comment] 2021-07-07 19:08
I can confirm that, at least on an iPad Mini 2 running iOS 12.5.4, that @LEJOUI's suggestion of using Safari and saving homeassistant.local to the homescreen (which hides the address bar) has solved this for me for now.

I was able to update HA to 2021.7.0 and am not experiencing any refreshes with this setup. The HA companion app still doesn't work, however.

**Comment by milkplus27** [comment] 2021-07-08 07:35
Had to revert back to 2021.5.5 and using the HA Companion app because the "Add to homescreen" method for Safari has no ability to manually refresh dashboards and I need to occasionally refresh due to some custom CSS elements in Lovelace.

Here's hoping @maykar manages to figure this out! I'm rooting for ya, bud.

**Comment by stephenmetts** [comment] 2021-07-08 13:08
I'm not sure if this is useful or not for anyone, but when my HA was auto-updated to version 2021.7, I found the constant refresh/crash issue in Fully Kiosk browser (running 1.7.1 of this add on) has stopped reproducing.  If anyone else was experiencing the issue under those conditions, I suggest upgrading your HA version.

**Comment by FidgetyRat** [comment] 2021-07-08 13:58
> I suggest upgrading your HA version.

I’m on 2021.7 and it still happens for me.

**Comment by milkplus27** [comment] 2021-07-16 12:26
anyone had any luck updating to 2021.7.3 to see if it fixes things?

**Comment by FidgetyRat** [comment] 2021-07-16 14:57
> anyone had any luck updating to 2021.7.3 to see if it fixes things?

I just did, and it appears to be working fine again (at least so far). I'd typically have the issue creep up after 10 seconds and it's been up for over 5 minutes now with no issues.

**Comment by milkplus27** [comment] 2021-07-19 11:19
> > anyone had any luck updating to 2021.7.3 to see if it fixes things?
> 
> I just did, and it appears to be working fine again (at least so far). I'd typically have the issue creep up after 10 seconds and it's been up for over 5 minutes now with no issues.

didn't work for me :( still refreshing like crazy and not correctly hiding headers upon refresh in the HA Companion app

I noticed in a previous comment your mentioned you're using a browser called WebFrame. Tried to install this (the free version at least) on my iPad Mini 2 but it says i need iOS13 at least - how did you manage to get it installed?

**Comment by FidgetyRat** [comment] 2021-07-19 12:05
> ...non my iPad Mini 2 but it says i need iOS13 at least - how did you manage to get it installed?

I'm running on an old iPhone 5S on 12.5.4. The latest versions of WebFrame require the later OS, but I was given the option to install the last compatible version.

Now, that said, when checking the OS version I quit WebFrame for the first time, and now it's back to refreshing constantly after about a week straight of NOT having the issue.. 

I did get it to finally go back to a state of not refreshing by first using safari and then switching back to WebFrame.

So yeah, I guess 2021.7.3 didn't have an effect after all. It was just a coincidence that I had been using safari briefly before updating. (Update: Nope, it's back again. Very random.)

Honestly, Kiosk Mode should be built into HA by default without having to jump through these kinds of hoops.

**Comment by milkplus27** [comment] 2021-08-06 04:07
Anyone had any success with 2021.8.1? I would love to use the new energy dashboard but not at the expense of all my tablets constantly refreshing!

**Comment by LEJOUI** [comment] 2021-08-06 10:07
The issue is still there.

**Comment by milkplus27** [comment] 2021-08-06 11:42
> The issue is still there.

Yup. Updated just to check but still prevalent in the HA companion app.

However, I have found that if I use Safari and save my HA dashboard to the home screen, I don't have the refreshing problem. However, I am not able to refresh at all in this mode, which I need to do occasionally for some of my hacked-together components haha.

If anyone knows of a way to refresh Lovelace from within Lovelace, like via a custom button, I would appreciate a heads up :)

**Comment by LEJOUI** [comment] 2021-08-06 12:36
> > The issue is still there.
> 
> Yup. Updated just to check but still prevalent in the HA companion app.
> 
> However, I have found that if I use Safari and save my HA dashboard to the home screen, I don't have the refreshing problem. However, I am not able to refresh at all in this mode, which I need to do occasionally for some of my hacked-together components haha.
> 
> If anyone knows of a way to refresh Lovelace from within Lovelace, like via a custom button, I would appreciate a heads up :)

Quick Google, did you try `browser_mod`? https://github.com/thomasloven/hass-browser_mod#available-commands

It has a service `lovelace_reload`. You could add this service to a button.

**Comment by steveguitar78** [comment] 2021-08-21 17:30
Hi all, same issue. No news?
Thank you

**Comment by LEJOUI** [comment] 2021-08-27 09:18
In beta 2021.9.0b1 the issue seems to be gone. I’ll monitor the performance but it looks very promising!

**Comment by milkplus27** [comment] 2021-08-27 09:37
> In beta 2021.9.0b1 the issue seems to be gone. I’ll monitor the performance but it looks very promising!

that's very exciting news! keep us posted!

**Comment by milkplus27** [comment] 2021-08-27 09:46
I wonder if it has anything to do with me logging the issue officially: https://github.com/home-assistant/frontend/issues/9803

was closed over a week ago...

**Comment by steveguitar78** [comment] 2021-08-27 10:37
> In beta 2021.9.0b1 the issue seems to be gone. I’ll monitor the performance but it looks very promising!

I hope it! thanks

**Comment by milkplus27** [comment] 2021-08-31 13:17
> In beta 2021.9.0b1 the issue seems to be gone. I’ll monitor the performance but it looks very promising!

Still looking solid @LEJOUI? here's hoping!

**Comment by LEJOUI** [comment] 2021-08-31 13:21
Yes! Now on b6 and everything is still going strong!

**Comment by milkplus27** [comment] 2021-08-31 13:51
> Yes! Now on b6 and everything is still going strong!

maaaan, this is music to my ears! how does one get on the beta? or is it just worth waiting for the official release? I assume that will be in the next week or so...

**Comment by LEJOUI** [comment] 2021-08-31 14:08
You can get the beta joining the beta channel in the system tab of the supervisor panel. 
Stable release is tomorrow btw.

**Comment by milkplus27** [comment] 2021-08-31 14:13
Right on. In that case I reckon I'll just wait haha

**Comment by maykar** [comment] 2021-08-31 15:31
I apologize for my radio silence on this issue. I was able to recreate it and tried many things to fix it. Closest I got was having kiosk mode restored after the refreshes happen, but the header would appear for a moment and the layout would flash and rearrange on every refresh. 

Glad to hear that there is a fix incoming and I may have been just chasing ghosts. I'll check beta tonight if I can, if not will jump on Stable tomorrow. On release, please confirm and we can close this one and never speak of it again :)

**Comment by milkplus27** [comment] 2021-09-01 22:23
Just wanted to say that I updated HA to 2021.9.0 and it looks like we might be in business! Still monitoring things, but so far haven't experienced any random refreshes or the header reappearing on any of my 4 iPad Mini 2s, especially after I reset the frontend cache.

Thanks @maykar for trying to fix things from your end. It's been unpleasant to have lived with a non-functioning dashboard/HA since May (!). Your efforts are appreciated even if it did turn out the issue was outside of your control.

**Comment by LEJOUI** [comment] 2021-09-02 06:29
No need to apologize @maykar. We do this in our own time and only work on it if we have the time for it. 
Looks like we can close this issue!

**Closed as completed** 2021-09-17 17:57 UTC
